package com.andymcsherry.ncaarankings;
import java.util.HashSet;
import java.util.Set;

public class Data {
    
    public static String[][] SCORES = new String[][] {
    { "North Carolina", "10", "South Carolina", "27" },
    { "Nevada-Las Vegas", "23", "Minnesota", "51" },
    { "Tulsa", "7", "Bowling Green", "34" },
    { "Akron", "7", "U-C-F", "38" },
    { "Utah State", "26", "Utah", "30" },
    { "Mississippi", "39", "Vanderbilt", "35" },
    { "Rutgers", "51", "Fresno State", "52" },
    { "Southern Cal", "30", "Hawaii", "13" },
    { "Sacramento State", "0", "San Jose State", "24" },
    { "Liberty", "10", "Kent State", "17" },
    { "Presbyterian", "7", "Wake Forest", "31" },
    { "Illinois State", "28", "Ball State", "51" },
    { "Indiana State", "35", "Indiana", "73" },
    { "Southern Utah", "22", "South Alabama", "21" },
    { "Towson", "33", "Connecticut", "18" },
    { "Western Carolina", "24", "Middle Tennessee", "45" },
    { "Jackson State", "7", "Tulane", "34" },
    { "Western Michigan", "13", "Michigan State", "26" },
    { "Florida Atlantic", "6", "Miami-Florida", "34" },
    { "Texas Tech", "41", "S-M-U", "23" },
    { "Morgan State", "12", "Army", "28" },
    { "Samford", "31", "Georgia State", "21" },
    { "North Dakota St", "24", "Kansas State", "21" },
    { "Southern Univ", "13", "Houston", "62" },
    { "Northern Arizona", "0", "Arizona", "35" },
    { "Massachusetts", "0", "Wisconsin", "45" },
    { "Central Michigan", "9", "Michigan", "59" },
    { "Buffalo", "20", "Ohio State", "40" },
    { "Louisiana Tech", "14", "No Carolina State", "40" },
    { "Florida Intl", "10", "Maryland", "43" },
    { "Northern Illinois", "30", "Iowa", "27" },
    { "Temple", "6", "Notre Dame", "28" },
    { "Brigham Young", "16", "Virginia", "19" },
    { "Alabama", "35", "Virginia Tech", "10" },
    { "U-A-B", "31", "Troy", "34" },
    { "Purdue", "7", "Cincinnati", "42" },
    { "Kentucky", "26", "Western Kentucky", "35" },
    { "Miami-Ohio", "14", "Marshall", "52" },
    { "Mississippi State", "3", "Oklahoma State", "21" },
    { "UL-Monroe", "0", "Oklahoma", "34" },
    { "Texas State", "22", "Southern Miss", "15" },
    { "New Mexico State", "7", "Texas", "56" },
    { "Rice", "31", "Texas A+M", "52" },
    { "Toledo", "6", "Florida", "24" },
    { "UL-Lafayette", "14", "Arkansas", "34" },
    { "Washington State", "24", "Auburn", "31" },
    { "Idaho", "6", "North Texas", "40" },
    { "Penn State", "23", "Syracuse", "17" },
    { "Wyoming", "34", "Nebraska", "37" },
    { "Texas-San Antonio", "21", "New Mexico", "13" },
    { "Georgia", "35", "Clemson", "38" },
    { "Louisiana State", "37", "Texas Christian", "27" },
    { "Boise State", "6", "Washington", "38" },
    { "Nevada-Reno", "20", "U.C.L.A.", "58" },
    { "Northwestern", "44", "California", "30" },
    { "Arkansas-Pine Bluff", "11", "Arkansas State", "62" },
    { "Colgate", "13", "Air Force", "38" },
    { "Elon", "0", "Georgia Tech", "70" },
    { "Murray State", "14", "Missouri", "58" },
    { "Austin Peay", "0", "Tennessee", "45" },
    { "Southern Illinois", "34", "Illinois", "42" },
    { "Villanova", "14", "Boston College", "24" },
    { "William + Mary", "17", "West Virginia", "24" },
    { "No Carolina Central", "0", "Duke", "45" },
    { "Nicholls State", "3", "Oregon", "66" },
    { "Eastern Washington", "49", "Oregon State", "46" },
    { "Howard", "24", "Eastern Michigan", "34" },
    { "McNeese State", "53", "South Florida", "21" },
    { "Old Dominion", "38", "East Carolina", "52" },
    { "Wofford", "3", "Baylor", "69" },
    { "Eastern Illinois", "40", "San Diego State", "19" },
    { "Northern Iowa", "28", "Iowa State", "20" },
    { "Ohio", "7", "Louisville", "49" },
    { "Colorado", "41", "Colorado State", "27" },
    { "Florida State", "41", "Pittsburgh", "13" },
    { "Florida Atlantic", "13", "East Carolina", "31" },
    { "Sacramento State", "0", "Arizona State", "55" },
    { "Wake Forest", "10", "Boston College", "24" },
    { "U-C-F", "38", "Florida Intl", "0" },
    { "Florida", "16", "Miami-Florida", "21" },
    { "Miami-Ohio", "7", "Kentucky", "41" },
    { "South Florida", "6", "Michigan State", "21" },
    { "Oklahoma State", "56", "Texas-San Antonio", "35" },
    { "Houston", "22", "Temple", "13" },
    { "North Texas", "21", "Ohio", "27" },
    { "Middle Tennessee", "20", "North Carolina", "40" },
    { "Cincinnati", "17", "Illinois", "45" },
    { "West Virginia", "7", "Oklahoma", "16" },
    { "South Carolina", "30", "Georgia", "41" },
    { "San Diego State", "7", "Ohio State", "42" },
    { "Utah State", "52", "Air Force", "20" },
    { "South Alabama", "41", "Tulane", "39" },
    { "Oregon", "59", "Virginia", "10" },
    { "Duke", "28", "Memphis", "14" },
    { "Syracuse", "27", "Northwestern", "48" },
    { "Navy", "41", "Indiana", "35" },
    { "Southern Miss", "13", "Nebraska", "56" },
    { "Texas", "21", "Brigham Young", "40" },
    { "U-A-B", "17", "Louisiana State", "56" },
    { "Toledo", "23", "Missouri", "38" },
    { "Colorado State", "27", "Tulsa", "30" },
    { "Arkansas State", "9", "Auburn", "38" },
    { "Army", "14", "Ball State", "40" },
    { "Eastern Michigan", "7", "Penn State", "45" },
    { "Buffalo", "13", "Baylor", "70" },
    { "Bowling Green", "41", "Kent State", "22" },
    { "Western Kentucky", "20", "Tennessee", "52" },
    { "UL-Lafayette", "27", "Kansas State", "48" },
    { "Notre Dame", "30", "Michigan", "41" },
    { "Hawaii", "14", "Oregon State", "33" },
    { "Minnesota", "44", "New Mexico State", "21" },
    { "Idaho", "10", "Wyoming", "42" },
    { "New Mexico", "42", "UTEP", "35" },
    { "Washington State", "10", "Southern Cal", "7" },
    { "Arizona", "58", "Nevada-Las Vegas", "13" },
    { "San Jose State", "13", "Stanford", "34" },
    { "Eastern Kentucky", "7", "Louisville", "44" },
    { "Indiana State", "14", "Purdue", "20" },
    { "Norfolk State", "0", "Rutgers", "38" },
    { "Samford", "21", "Arkansas", "31" },
    { "S E Louisiana", "17", "Texas Christian", "38" },
    { "Sam Houston State", "28", "Texas A+M", "65" },
    { "Missouri State", "14", "Iowa", "28" },
    { "Tennessee Tech", "0", "Wisconsin", "48" },
    { "So Carolina State", "13", "Clemson", "52" },
    { "Western Carolina", "3", "Virginia Tech", "45" },
    { "Chattanooga", "42", "Georgia State", "14" },
    { "Maine", "24", "Massachusetts", "14" },
    { "Weber State", "7", "Utah", "70" },
    { "New Hampshire", "21", "Central Michigan", "24" },
    { "Tennessee-Martin", "14", "Boise State", "63" },
    { "Alcorn State", "7", "Mississippi State", "51" },
    { "Old Dominion", "10", "Maryland", "47" },
    { "Portland State", "30", "California", "37" },
    { "James Madison", "33", "Akron", "35" },
    { "Richmond", "21", "No Carolina State", "23" },
    { "Gardner-Webb", "0", "Marshall", "55" },
    { "Stephen F Austin", "13", "Texas Tech", "61" },
    { "Grambling", "10", "UL-Monroe", "48" },
    { "Lamar", "14", "Louisiana Tech", "27" },
    { "Nicholls State", "27", "Western Michigan", "23" },
    { "Prairie View", "3", "Texas State", "28" },
    { "Savannah State", "3", "Troy", "66" },
    { "South Dakota", "14", "Kansas", "31" },
    { "Central Arkansas", "24", "Colorado", "38" },
    { "Montana State", "30", "S-M-U", "31" },
    { "Austin Peay", "3", "Vanderbilt", "38" },
    { "S E Missouri St", "13", "Mississippi", "31" },
    { "UC-Davis", "7", "Nevada-Reno", "36" },
    { "Cal-San Luis Obispo", "25", "Fresno State", "41" },
    { "Texas Christian", "10", "Texas Tech", "20" },
    { "Tulane", "24", "Louisiana Tech", "15" },
    { "Troy", "34", "Arkansas State", "41" },
    { "Air Force", "20", "Boise State", "42" },
    { "Eastern Michigan", "10", "Rutgers", "28" },
    { "Stanford", "34", "Army", "20" },
    { "Georgia State", "7", "West Virginia", "41" },
    { "Louisville", "27", "Kentucky", "13" },
    { "Marshall", "31", "Ohio", "34" },
    { "Akron", "24", "Michigan", "28" },
    { "Bowling Green", "10", "Indiana", "42" },
    { "Virginia Tech", "15", "East Carolina", "10" },
    { "Maryland", "32", "Connecticut", "21" },
    { "New Mexico", "27", "Pittsburgh", "49" },
    { "UL-Monroe", "21", "Wake Forest", "19" },
    { "Western Kentucky", "24", "South Alabama", "31" },
    { "Nevada-Reno", "7", "Florida State", "62" },
    { "U.C.L.A.", "41", "Nebraska", "21" },
    { "Georgia Tech", "38", "Duke", "14" },
    { "Tennessee", "14", "Oregon", "59" },
    { "Mississippi", "44", "Texas", "23" },
    { "Boston College", "7", "Southern Cal", "35" },
    { "Iowa", "27", "Iowa State", "21" },
    { "Alabama", "49", "Texas A+M", "42" },
    { "Northern Illinois", "45", "Idaho", "35" },
    { "Mississippi State", "20", "Auburn", "24" },
    { "Washington", "34", "Illinois", "24" },
    { "U-C-F", "34", "Penn State", "31" },
    { "Ball State", "27", "North Texas", "34" },
    { "Memphis", "15", "Middle Tennessee", "17" },
    { "Southern Miss", "3", "Arkansas", "24" },
    { "Vanderbilt", "25", "South Carolina", "35" },
    { "Tulsa", "20", "Oklahoma", "51" },
    { "Ohio State", "52", "California", "34" },
    { "Massachusetts", "7", "Kansas State", "37" },
    { "Florida Atlantic", "28", "South Florida", "10" },
    { "Kansas", "14", "Rice", "23" },
    { "Kent State", "13", "Louisiana State", "45" },
    { "Notre Dame", "31", "Purdue", "24" },
    { "UTEP", "42", "New Mexico State", "21" },
    { "Western Michigan", "17", "Northwestern", "38" },
    { "Texas-San Antonio", "13", "Arizona", "38" },
    { "Oregon State", "51", "Utah", "48" },
    { "Central Michigan", "21", "Nevada-Las Vegas", "31" },
    { "Wisconsin", "30", "Arizona State", "32" },
    { "Western Illinois", "12", "Minnesota", "29" },
    { "Fordham", "30", "Temple", "29" },
    { "Youngstown State", "17", "Michigan State", "55" },
    { "Delaware", "7", "Navy", "51" },
    { "Stony Brook", "23", "Buffalo", "26" },
    { "Wagner", "0", "Syracuse", "54" },
    { "Bethune-Cookman", "34", "Florida Intl", "13" },
    { "Cal-San Luis Obispo", "17", "Colorado State", "34" },
    { "Eastern Washington", "21", "Toledo", "33" },
    { "Nicholls State", "7", "UL-Lafayette", "70" },
    { "Northwestern St(LA)", "9", "Cincinnati", "66" },
    { "Lamar", "3", "Oklahoma State", "59" },
    { "Northern Colorado", "7", "Wyoming", "35" },
    { "Weber State", "6", "Utah State", "70" },
    { "Southern Utah", "10", "Washington State", "48" },
    { "Clemson", "26", "No Carolina State", "14" },
    { "Boise State", "40", "Fresno State", "41" },
    { "North Texas", "21", "Georgia", "45" },
    { "Florida Intl", "0", "Louisville", "72" },
    { "Western Michigan", "3", "Iowa", "59" },
    { "Vanderbilt", "24", "Massachusetts", "7" },
    { "Tennessee", "17", "Florida", "31" },
    { "Wake Forest", "25", "Army", "11" },
    { "Pittsburgh", "58", "Duke", "55" },
    { "Michigan", "24", "Connecticut", "21" },
    { "Purdue", "10", "Wisconsin", "41" },
    { "Ball State", "51", "Eastern Michigan", "20" },
    { "Kent State", "0", "Penn State", "34" },
    { "Marshall", "21", "Virginia Tech", "29" },
    { "Cincinnati", "14", "Miami-Ohio", "0" },
    { "North Carolina", "20", "Georgia Tech", "28" },
    { "West Virginia", "0", "Maryland", "37" },
    { "San Jose State", "24", "Minnesota", "43" },
    { "Troy", "7", "Mississippi State", "62" },
    { "UL-Monroe", "7", "Baylor", "70" },
    { "Wyoming", "56", "Air Force", "23" },
    { "Utah", "20", "Brigham Young", "13" },
    { "Hawaii", "9", "Nevada-Reno", "31" },
    { "Utah State", "14", "Southern Cal", "17" },
    { "S-M-U", "13", "Texas A+M", "42" },
    { "Rice", "26", "Houston", "31" },
    { "Michigan State", "13", "Notre Dame", "17" },
    { "Kansas State", "21", "Texas", "31" },
    { "Arkansas State", "7", "Memphis", "31" },
    { "Louisiana Tech", "10", "Kansas", "13" },
    { "Colorado State", "6", "Alabama", "31" },
    { "Arkansas", "24", "Rutgers", "28" },
    { "Arizona State", "28", "Stanford", "42" },
    { "UL-Lafayette", "35", "Akron", "30" },
    { "Idaho", "0", "Washington State", "42" },
    { "Middle Tennessee", "42", "Florida Atlantic", "35" },
    { "Tulane", "17", "Syracuse", "52" },
    { "Toledo", "38", "Central Michigan", "17" },
    { "Texas State", "7", "Texas Tech", "33" },
    { "Oregon State", "34", "San Diego State", "30" },
    { "Auburn", "21", "Louisiana State", "35" },
    { "Texas-San Antonio", "32", "UTEP", "13" },
    { "Missouri", "45", "Indiana", "28" },
    { "New Mexico State", "13", "U.C.L.A.", "59" },
    { "Savannah State", "7", "Miami-Florida", "77" },
    { "South Dakota State", "20", "Nebraska", "59" },
    { "Jacksonville St", "32", "Georgia State", "26" },
    { "Austin Peay", "0", "Ohio", "38" },
    { "Northwestern St(LA)", "28", "U-A-B", "52" },
    { "Bethune-Cookman", "6", "Florida State", "54" },
    { "Murray State", "7", "Bowling Green", "48" },
    { "Virginia Military", "0", "Virginia", "49" },
    { "Idaho State", "0", "Washington", "56" },
    { "Eastern Illinois", "39", "Northern Illinois", "43" },
    { "Florida A+M", "0", "Ohio State", "76" },
    { "Morgan State", "17", "Western Kentucky", "58" },
    { "Maine", "21", "Northwestern", "35" },
    { "Western Illinois", "7", "Nevada-Las Vegas", "38" },
    { "Virginia Tech", "17", "Georgia Tech", "10" },
    { "Iowa State", "38", "Tulsa", "21" },
    { "Middle Tennessee", "10", "Brigham Young", "37" },
    { "Utah State", "40", "San Jose State", "12" },
    { "Virginia", "3", "Pittsburgh", "14" },
    { "Northern Illinois", "55", "Purdue", "24" },
    { "Troy", "31", "Duke", "38" },
    { "Connecticut", "12", "Buffalo", "41" },
    { "Toledo", "24", "Ball State", "31" },
    { "Central Michigan", "14", "No Carolina State", "48" },
    { "Kent State", "32", "Western Michigan", "14" },
    { "East Carolina", "55", "North Carolina", "31" },
    { "Florida State", "48", "Boston College", "34" },
    { "U-A-B", "24", "Vanderbilt", "52" },
    { "Miami-Ohio", "14", "Illinois", "50" },
    { "S-M-U", "17", "Texas Christian", "48" },
    { "Arkansas State", "19", "Missouri", "41" },
    { "Iowa", "23", "Minnesota", "7" },
    { "UTEP", "42", "Colorado State", "59" },
    { "Louisiana State", "41", "Georgia", "44" },
    { "Arizona", "13", "Washington", "31" },
    { "Mississippi", "0", "Alabama", "25" },
    { "California", "16", "Oregon", "55" },
    { "Southern Cal", "41", "Arizona State", "62" },
    { "Army", "35", "Louisiana Tech", "16" },
    { "Texas A+M", "45", "Arkansas", "33" },
    { "Oklahoma", "35", "Notre Dame", "21" },
    { "Southern Miss", "7", "Boise State", "60" },
    { "Miami-Florida", "49", "South Florida", "21" },
    { "Wake Forest", "7", "Clemson", "56" },
    { "Temple", "24", "Idaho", "26" },
    { "Tulane", "31", "UL-Monroe", "14" },
    { "Houston", "59", "Texas-San Antonio", "28" },
    { "Akron", "14", "Bowling Green", "31" },
    { "Colorado", "17", "Oregon State", "44" },
    { "South Carolina", "28", "U-C-F", "25" },
    { "Florida", "24", "Kentucky", "7" },
    { "Stanford", "55", "Washington State", "17" },
    { "Wyoming", "21", "Texas State", "42" },
    { "Navy", "7", "Western Kentucky", "19" },
    { "Florida Atlantic", "14", "Rice", "18" },
    { "South Alabama", "24", "Tennessee", "31" },
    { "Air Force", "42", "Nevada-Reno", "45" },
    { "Oklahoma State", "21", "West Virginia", "30" },
    { "Wisconsin", "24", "Ohio State", "31" },
    { "Nevada-Las Vegas", "56", "New Mexico", "42" },
    { "San Diego State", "26", "New Mexico State", "16" },
    { "Fresno State", "42", "Hawaii", "37" },
    { "Texas", "31", "Iowa State", "30" },
    { "Western Kentucky", "31", "UL-Monroe", "10" },
    { "U.C.L.A.", "34", "Utah", "27" },
    { "Brigham Young", "31", "Utah State", "14" },
    { "Nevada-Reno", "44", "San Diego State", "51" },
    { "Air Force", "10", "Navy", "28" },
    { "Michigan State", "26", "Iowa", "14" },
    { "Louisville", "30", "Temple", "7" },
    { "Western Michigan", "20", "Toledo", "47" },
    { "Eastern Michigan", "14", "Buffalo", "42" },
    { "Georgia State", "3", "Alabama", "45" },
    { "Army", "27", "Boston College", "48" },
    { "Central Michigan", "21", "Miami-Ohio", "9" },
    { "Ball State", "48", "Virginia", "27" },
    { "Maryland", "0", "Florida State", "63" },
    { "Georgia Tech", "30", "Miami-Florida", "45" },
    { "Clemson", "49", "Syracuse", "14" },
    { "No Carolina State", "13", "Wake Forest", "28" },
    { "Illinois", "19", "Nebraska", "39" },
    { "Texas-San Antonio", "10", "Marshall", "34" },
    { "North Texas", "21", "Tulane", "24" },
    { "Oregon", "57", "Colorado", "16" },
    { "Georgia", "34", "Tennessee", "31" },
    { "Arkansas", "10", "Florida", "30" },
    { "Louisiana State", "59", "Mississippi State", "26" },
    { "Rice", "30", "Tulsa", "27" },
    { "North Carolina", "17", "Virginia Tech", "27" },
    { "Texas Christian", "17", "Oklahoma", "20" },
    { "Cincinnati", "20", "South Florida", "26" },
    { "Kansas State", "29", "Oklahoma State", "33" },
    { "Missouri", "51", "Vanderbilt", "28" },
    { "Minnesota", "13", "Michigan", "42" },
    { "U-C-F", "24", "Memphis", "17" },
    { "Rutgers", "55", "S-M-U", "52" },
    { "Fresno State", "61", "Idaho", "14" },
    { "Texas State", "24", "UL-Lafayette", "48" },
    { "South Alabama", "33", "Troy", "34" },
    { "New Mexico State", "17", "New Mexico", "66" },
    { "Washington State", "44", "California", "22" },
    { "Washington", "28", "Stanford", "31" },
    { "Northern Illinois", "38", "Kent State", "24" },
    { "Mississippi", "22", "Auburn", "30" },
    { "Kentucky", "28", "South Carolina", "35" },
    { "Florida Intl", "24", "Southern Miss", "23" },
    { "Massachusetts", "7", "Bowling Green", "28" },
    { "Florida Atlantic", "37", "U-A-B", "23" },
    { "Texas Tech", "54", "Kansas", "16" },
    { "East Carolina", "24", "Middle Tennessee", "17" },
    { "Ohio", "43", "Akron", "3" },
    { "Arizona State", "34", "Notre Dame", "37" },
    { "West Virginia", "42", "Baylor", "73" },
    { "Louisiana Tech", "38", "UTEP", "35" },
    { "Ohio State", "40", "Northwestern", "30" },
    { "Penn State", "24", "Indiana", "44" },
    { "San Jose State", "37", "Hawaii", "27" },
    { "Rutgers", "10", "Louisville", "24" },
    { "San Diego State", "27", "Air Force", "20" },
    { "Arizona", "31", "Southern Cal", "38" },
    { "Temple", "20", "Cincinnati", "38" },
    { "Oklahoma", "20", "Texas", "36" },
    { "Indiana", "28", "Michigan State", "42" },
    { "Pittsburgh", "9", "Virginia Tech", "19" },
    { "Miami-Ohio", "10", "Massachusetts", "17" },
    { "Boston College", "14", "Clemson", "24" },
    { "Buffalo", "33", "Western Michigan", "0" },
    { "Central Michigan", "26", "Ohio", "23" },
    { "Eastern Michigan", "25", "Army", "50" },
    { "Virginia", "26", "Maryland", "27" },
    { "South Florida", "13", "Connecticut", "10" },
    { "Navy", "7", "Duke", "35" },
    { "Troy", "35", "Georgia State", "28" },
    { "Texas A+M", "41", "Mississippi", "38" },
    { "Kent State", "24", "Ball State", "27" },
    { "Bowling Green", "20", "Mississippi State", "21" },
    { "Akron", "20", "Northern Illinois", "27" },
    { "Iowa State", "35", "Texas Tech", "42" },
    { "Rice", "27", "Texas-San Antonio", "21" },
    { "New Mexico", "31", "Wyoming", "38" },
    { "Stanford", "21", "Utah", "27" },
    { "Georgia Tech", "20", "Brigham Young", "38" },
    { "Nebraska", "44", "Purdue", "7" },
    { "Missouri", "41", "Georgia", "26" },
    { "Baylor", "35", "Kansas State", "25" },
    { "Florida", "6", "Louisiana State", "17" },
    { "Colorado", "13", "Arizona State", "54" },
    { "Oregon", "45", "Washington", "24" },
    { "California", "10", "U.C.L.A.", "37" },
    { "Northwestern", "6", "Wisconsin", "35" },
    { "East Carolina", "33", "Tulane", "36" },
    { "South Carolina", "52", "Arkansas", "7" },
    { "Alabama", "48", "Kentucky", "7" },
    { "San Jose State", "34", "Colorado State", "27" },
    { "Idaho", "24", "Arkansas State", "48" },
    { "Michigan", "40", "Penn State", "43" },
    { "Syracuse", "24", "No Carolina State", "10" },
    { "Memphis", "15", "Houston", "25" },
    { "U-A-B", "27", "Florida Intl", "24" },
    { "Marshall", "24", "Florida Atlantic", "23" },
    { "Kansas", "17", "Texas Christian", "27" },
    { "Middle Tennessee", "7", "North Texas", "34" },
    { "UL-Monroe", "21", "Texas State", "14" },
    { "Boise State", "34", "Utah State", "23" },
    { "Oregon State", "52", "Washington State", "24" },
    { "Tulsa", "34", "UTEP", "20" },
    { "Hawaii", "37", "Nevada-Las Vegas", "39" },
    { "Western Carolina", "3", "Auburn", "62" },
    { "UL-Lafayette", "37", "Western Kentucky", "20" },
    { "Miami-Florida", "27", "North Carolina", "23" },
    { "U-C-F", "38", "Louisville", "35" },
    { "Duke", "35", "Virginia", "22" },
    { "Army", "14", "Temple", "33" },
    { "Ohio", "56", "Eastern Michigan", "28" },
    { "Ball State", "38", "Western Michigan", "17" },
    { "Northern Illinois", "38", "Central Michigan", "17" },
    { "Purdue", "0", "Michigan State", "14" },
    { "Southern Miss", "14", "East Carolina", "55" },
    { "Florida State", "51", "Clemson", "14" },
    { "Maryland", "10", "Wake Forest", "34" },
    { "Texas Tech", "37", "West Virginia", "27" },
    { "Minnesota", "20", "Northwestern", "17" },
    { "Navy", "44", "Toledo", "45" },
    { "Connecticut", "16", "Cincinnati", "41" },
    { "S-M-U", "34", "Memphis", "29" },
    { "Colorado State", "52", "Wyoming", "22" },
    { "Auburn", "45", "Texas A+M", "41" },
    { "Washington State", "38", "Oregon", "62" },
    { "Indiana", "47", "Michigan", "63" },
    { "Syracuse", "0", "Georgia Tech", "56" },
    { "Oregon State", "49", "California", "17" },
    { "Iowa", "24", "Ohio State", "34" },
    { "Arkansas", "0", "Alabama", "52" },
    { "South Carolina", "21", "Tennessee", "23" },
    { "Washington", "24", "Arizona State", "53" },
    { "North Texas", "28", "Louisiana Tech", "13" },
    { "Kent State", "21", "South Alabama", "38" },
    { "Utah State", "45", "New Mexico", "10" },
    { "Florida", "17", "Missouri", "36" },
    { "Louisiana State", "24", "Mississippi", "27" },
    { "Brigham Young", "47", "Houston", "46" },
    { "Massachusetts", "3", "Buffalo", "32" },
    { "Georgia State", "17", "Texas State", "24" },
    { "Akron", "24", "Miami-Ohio", "17" },
    { "Iowa State", "7", "Baylor", "71" },
    { "Oklahoma", "34", "Kansas", "19" },
    { "Texas Christian", "10", "Oklahoma State", "24" },
    { "U.C.L.A.", "10", "Stanford", "24" },
    { "Southern Cal", "10", "Notre Dame", "14" },
    { "Rice", "45", "New Mexico State", "19" },
    { "Nevada-Reno", "17", "Boise State", "34" },
    { "Wisconsin", "56", "Illinois", "32" },
    { "Georgia", "27", "Vanderbilt", "31" },
    { "Utah", "24", "Arizona", "35" },
    { "Nevada-Las Vegas", "14", "Fresno State", "38" },
    { "Old Dominion", "24", "Pittsburgh", "35" },
    { "Charleston Southern", "10", "Colorado", "43" },
    { "UL-Lafayette", "23", "Arkansas State", "7" },
    { "Kentucky", "22", "Mississippi State", "28" },
    { "Marshall", "49", "Middle Tennessee", "51" },
    { "Boise State", "20", "Brigham Young", "37" },
    { "Georgia Tech", "35", "Virginia", "25" },
    { "Connecticut", "17", "U-C-F", "62" },
    { "Ball State", "42", "Akron", "24" },
    { "Miami-Ohio", "16", "Ohio", "41" },
    { "Buffalo", "41", "Kent State", "21" },
    { "Western Michigan", "31", "Massachusetts", "30" },
    { "Houston", "49", "Rutgers", "14" },
    { "Boston College", "10", "North Carolina", "34" },
    { "Clemson", "40", "Maryland", "27" },
    { "Duke", "13", "Virginia Tech", "10" },
    { "Pittsburgh", "21", "Navy", "24" },
    { "U-A-B", "31", "Texas-San Antonio", "52" },
    { "Temple", "49", "S-M-U", "59" },
    { "Eastern Michigan", "20", "Northern Illinois", "59" },
    { "Arizona", "44", "Colorado", "20" },
    { "Vanderbilt", "24", "Texas A+M", "56" },
    { "Florida Atlantic", "10", "Auburn", "45" },
    { "Tennessee", "10", "Alabama", "45" },
    { "U.C.L.A.", "14", "Oregon", "42" },
    { "Utah", "3", "Southern Cal", "19" },
    { "Tulsa", "7", "Tulane", "14" },
    { "California", "17", "Washington", "41" },
    { "West Virginia", "12", "Kansas State", "35" },
    { "Michigan State", "42", "Illinois", "3" },
    { "Wake Forest", "21", "Miami-Florida", "24" },
    { "No Carolina State", "17", "Florida State", "49" },
    { "Texas Tech", "30", "Oklahoma", "38" },
    { "Texas", "30", "Texas Christian", "7" },
    { "Northwestern", "10", "Iowa", "17" },
    { "Nevada-Las Vegas", "27", "Nevada-Reno", "22" },
    { "Wyoming", "44", "San Jose State", "51" },
    { "Stanford", "20", "Oregon State", "12" },
    { "Troy", "32", "Western Kentucky", "26" },
    { "Notre Dame", "45", "Air Force", "10" },
    { "Georgia State", "10", "UL-Monroe", "38" },
    { "South Alabama", "31", "Texas State", "33" },
    { "Idaho", "14", "Mississippi", "59" },
    { "North Texas", "55", "Southern Miss", "14" },
    { "Louisiana Tech", "23", "Florida Intl", "7" },
    { "South Carolina", "27", "Missouri", "24" },
    { "Oklahoma State", "58", "Iowa State", "27" },
    { "Baylor", "59", "Kansas", "14" },
    { "Nebraska", "23", "Minnesota", "34" },
    { "Louisville", "34", "South Florida", "3" },
    { "Toledo", "28", "Bowling Green", "25" },
    { "Penn State", "14", "Ohio State", "63" },
    { "UTEP", "7", "Rice", "45" },
    { "Fresno State", "35", "San Diego State", "28" },
    { "Colorado State", "35", "Hawaii", "28" },
    { "Abilene Christian", "29", "New Mexico State", "34" },
    { "Furman", "16", "Louisiana State", "48" },
    { "Cincinnati", "34", "Memphis", "21" },
    { "South Florida", "23", "Houston", "35" },
    { "Rice", "16", "North Texas", "28" },
    { "UL-Monroe", "49", "Troy", "37" },
    { "Arizona State", "55", "Washington State", "21" },
    { "Southern Cal", "31", "Oregon State", "14" },
    { "Clemson", "59", "Virginia", "10" },
    { "Virginia Tech", "27", "Boston College", "34" },
    { "Eastern Michigan", "16", "Toledo", "55" },
    { "Northern Illinois", "63", "Massachusetts", "19" },
    { "Kent State", "7", "Akron", "16" },
    { "Temple", "20", "Rutgers", "23" },
    { "Illinois", "17", "Penn State", "24" },
    { "Pittsburgh", "10", "Georgia Tech", "21" },
    { "Wake Forest", "0", "Syracuse", "13" },
    { "Western Kentucky", "44", "Georgia State", "28" },
    { "Tennessee", "3", "Missouri", "31" },
    { "Iowa State", "7", "Kansas State", "41" },
    { "Southern Miss", "13", "Marshall", "61" },
    { "UTEP", "7", "Texas A+M", "57" },
    { "Middle Tennessee", "24", "U-A-B", "21" },
    { "Texas-San Antonio", "34", "Tulsa", "15" },
    { "Army", "28", "Air Force", "42" },
    { "West Virginia", "30", "Texas Christian", "27" },
    { "Georgia", "23", "Florida", "20" },
    { "Arizona", "33", "California", "28" },
    { "Miami-Florida", "14", "Florida State", "41" },
    { "Wisconsin", "28", "Iowa", "9" },
    { "Michigan", "6", "Michigan State", "29" },
    { "Ohio State", "56", "Purdue", "0" },
    { "Minnesota", "42", "Indiana", "39" },
    { "Colorado", "23", "U.C.L.A.", "45" },
    { "Navy", "34", "Notre Dame", "38" },
    { "Auburn", "35", "Arkansas", "17" },
    { "Northwestern", "24", "Nebraska", "27" },
    { "Arkansas State", "17", "South Alabama", "16" },
    { "Hawaii", "10", "Utah State", "47" },
    { "San Jose State", "34", "Nevada-Las Vegas", "24" },
    { "New Mexico State", "35", "UL-Lafayette", "49" },
    { "Texas State", "37", "Idaho", "21" },
    { "North Carolina", "27", "No Carolina State", "19" },
    { "Kansas", "13", "Texas", "35" },
    { "Tulane", "17", "Florida Atlantic", "34" },
    { "Oklahoma State", "52", "Texas Tech", "34" },
    { "East Carolina", "34", "Florida Intl", "13" },
    { "Nevada-Reno", "23", "Fresno State", "41" },
    { "Mississippi State", "16", "South Carolina", "34" },
    { "Boise State", "42", "Colorado State", "30" },
    { "New Mexico", "30", "San Diego State", "35" },
    { "Alabama State", "14", "Kentucky", "48" },
    { "Ohio", "3", "Buffalo", "30" },
    { "Bowling Green", "45", "Miami-Ohio", "3" },
    { "Central Michigan", "24", "Ball State", "44" },
    { "Oklahoma", "12", "Baylor", "41" },
    { "Troy", "36", "UL-Lafayette", "41" },
    { "Oregon", "20", "Stanford", "26" },
    { "Louisville", "31", "Connecticut", "10" },
    { "Air Force", "37", "New Mexico", "45" },
    { "Iowa", "38", "Purdue", "14" },
    { "Western Kentucky", "21", "Army", "17" },
    { "S-M-U", "25", "Cincinnati", "28" },
    { "No Carolina State", "20", "Duke", "38" },
    { "Tulsa", "24", "East Carolina", "58" },
    { "Illinois", "35", "Indiana", "52" },
    { "Texas Christian", "21", "Iowa State", "17" },
    { "Florida State", "59", "Wake Forest", "3" },
    { "U-A-B", "14", "Marshall", "56" },
    { "Virginia Tech", "42", "Miami-Florida", "24" },
    { "Penn State", "10", "Minnesota", "24" },
    { "Syracuse", "20", "Maryland", "3" },
    { "Missouri", "48", "Kentucky", "17" },
    { "Virginia", "14", "North Carolina", "45" },
    { "Vanderbilt", "34", "Florida", "17" },
    { "Western Michigan", "32", "Eastern Michigan", "35" },
    { "Tulane", "7", "Texas-San Antonio", "10" },
    { "Fresno State", "48", "Wyoming", "10" },
    { "Kansas State", "49", "Texas Tech", "26" },
    { "Brigham Young", "17", "Wisconsin", "27" },
    { "Arkansas", "24", "Mississippi", "34" },
    { "Nevada-Reno", "17", "Colorado State", "38" },
    { "Colorado", "7", "Washington", "59" },
    { "Texas", "47", "West Virginia", "40" },
    { "Arizona State", "20", "Utah", "19" },
    { "Nebraska", "17", "Michigan", "13" },
    { "Hawaii", "28", "Navy", "42" },
    { "UTEP", "7", "North Texas", "41" },
    { "Kansas", "6", "Oklahoma State", "42" },
    { "Southern Cal", "62", "California", "28" },
    { "Notre Dame", "21", "Pittsburgh", "28" },
    { "Mississippi State", "41", "Texas A+M", "51" },
    { "Boston College", "48", "New Mexico State", "34" },
    { "Utah State", "28", "Nevada-Las Vegas", "24" },
    { "Florida Intl", "0", "Middle Tennessee", "48" },
    { "Arkansas State", "42", "UL-Monroe", "14" },
    { "Southern Miss", "13", "Louisiana Tech", "36" },
    { "Auburn", "55", "Tennessee", "23" },
    { "Houston", "14", "U-C-F", "19" },
    { "U.C.L.A.", "31", "Arizona", "26" },
    { "Louisiana State", "17", "Alabama", "38" },
    { "San Diego State", "34", "San Jose State", "30" },
    { "Appalachian State", "6", "Georgia", "45" },
    { "Tennessee-Martin", "6", "Memphis", "21" },
    { "Old Dominion", "59", "Idaho", "38" },
    { "Ohio", "0", "Bowling Green", "49" },
    { "Buffalo", "41", "Toledo", "51" },
    { "Ball State", "27", "Northern Illinois", "48" },
    { "Miami-Ohio", "6", "Kent State", "24" },
    { "Georgia Tech", "31", "Clemson", "55" },
    { "Marshall", "45", "Tulsa", "34" },
    { "Washington", "31", "U.C.L.A.", "41" },
    { "Miami-Florida", "30", "Duke", "48" },
    { "Indiana", "3", "Wisconsin", "51" },
    { "Kentucky", "6", "Vanderbilt", "22" },
    { "Houston", "13", "Louisville", "20" },
    { "Central Michigan", "27", "Western Michigan", "22" },
    { "Maryland", "27", "Virginia Tech", "24" },
    { "No Carolina State", "21", "Boston College", "38" },
    { "Cincinnati", "52", "Rutgers", "17" },
    { "North Carolina", "34", "Pittsburgh", "27" },
    { "U-C-F", "39", "Temple", "36" },
    { "Purdue", "21", "Penn State", "45" },
    { "Florida", "14", "South Carolina", "19" },
    { "Michigan", "27", "Northwestern", "19" },
    { "Syracuse", "3", "Florida State", "59" },
    { "Florida Atlantic", "41", "Southern Miss", "7" },
    { "Akron", "14", "Massachusetts", "13" },
    { "U-A-B", "14", "East Carolina", "63" },
    { "Connecticut", "21", "S-M-U", "38" },
    { "West Virginia", "19", "Kansas", "31" },
    { "UL-Lafayette", "35", "Georgia State", "21" },
    { "California", "24", "Colorado", "41" },
    { "Texas Tech", "34", "Baylor", "63" },
    { "Wyoming", "7", "Boise State", "48" },
    { "Oregon State", "17", "Arizona State", "30" },
    { "Georgia", "38", "Auburn", "43" },
    { "Oklahoma State", "38", "Texas", "13" },
    { "Iowa State", "10", "Oklahoma", "48" },
    { "Utah", "21", "Oregon", "44" },
    { "South Alabama", "14", "Navy", "42" },
    { "Michigan State", "41", "Nebraska", "28" },
    { "Ohio State", "60", "Illinois", "35" },
    { "San Jose State", "16", "Nevada-Reno", "38" },
    { "Alabama", "20", "Mississippi State", "7" },
    { "Stanford", "17", "Southern Cal", "20" },
    { "Colorado State", "66", "New Mexico", "42" },
    { "Memphis", "23", "South Florida", "10" },
    { "Louisiana Tech", "14", "Rice", "52" },
    { "Texas Christian", "31", "Kansas State", "33" },
    { "Troy", "21", "Mississippi", "51" },
    { "Texas State", "21", "Arkansas State", "38" },
    { "Florida Intl", "10", "UTEP", "33" },
    { "Washington State", "24", "Arizona", "17" },
    { "San Diego State", "28", "Hawaii", "21" },
    { "Idaho State", "13", "Brigham Young", "59" },
    { "Buffalo", "44", "Miami-Ohio", "7" },
    { "Kent State", "44", "Ohio", "13" },
    { "Northern Illinois", "35", "Toledo", "17" },
    { "Rutgers", "17", "U-C-F", "41" },
    { "Rice", "37", "U-A-B", "34" },
    { "Nevada-Las Vegas", "41", "Air Force", "21" },
    { "Navy", "58", "San Jose State", "52" },
    { "Nebraska", "23", "Penn State", "20" },
    { "Illinois", "20", "Purdue", "16" },
    { "Pittsburgh", "17", "Syracuse", "16" },
    { "Connecticut", "28", "Temple", "21" },
    { "Indiana", "14", "Ohio State", "42" },
    { "Michigan State", "30", "Northwestern", "6" },
    { "East Carolina", "42", "No Carolina State", "28" },
    { "Idaho", "14", "Florida State", "80" },
    { "Marshall", "48", "Florida Intl", "10" },
    { "Kentucky", "17", "Georgia", "59" },
    { "Kansas", "0", "Iowa State", "34" },
    { "Duke", "28", "Wake Forest", "21" },
    { "Boston College", "29", "Maryland", "26" },
    { "Wisconsin", "20", "Minnesota", "7" },
    { "Virginia", "26", "Miami-Florida", "45" },
    { "Cincinnati", "24", "Houston", "17" },
    { "Memphis", "17", "Louisville", "24" },
    { "Vanderbilt", "14", "Tennessee", "10" },
    { "Massachusetts", "0", "Central Michigan", "37" },
    { "Bowling Green", "58", "Eastern Michigan", "7" },
    { "Hawaii", "56", "Wyoming", "59" },
    { "Western Kentucky", "37", "Texas State", "7" },
    { "Michigan", "21", "Iowa", "24" },
    { "Arizona State", "38", "U.C.L.A.", "33" },
    { "Colorado State", "0", "Utah State", "13" },
    { "Southern Cal", "47", "Colorado", "29" },
    { "Texas A+M", "10", "Louisiana State", "34" },
    { "Mississippi State", "24", "Arkansas", "17" },
    { "Oregon", "16", "Arizona", "42" },
    { "UTEP", "3", "Tulane", "45" },
    { "California", "13", "Stanford", "63" },
    { "Texas-San Antonio", "21", "North Texas", "13" },
    { "Brigham Young", "13", "Notre Dame", "23" },
    { "Baylor", "17", "Oklahoma State", "49" },
    { "Middle Tennessee", "42", "Southern Miss", "21" },
    { "Georgia State", "33", "Arkansas State", "35" },
    { "Washington", "69", "Oregon State", "27" },
    { "UL-Monroe", "14", "South Alabama", "36" },
    { "S-M-U", "16", "South Florida", "6" },
    { "New Mexico", "28", "Fresno State", "69" },
    { "New Mexico State", "10", "Florida Atlantic", "55" },
    { "Tulsa", "24", "Louisiana Tech", "14" },
    { "Oklahoma", "41", "Kansas State", "31" },
    { "Missouri", "24", "Mississippi", "10" },
    { "Utah", "37", "Washington State", "49" },
    { "Boise State", "31", "San Diego State", "34" },
    { "Old Dominion", "20", "North Carolina", "80" },
    { "Chattanooga", "0", "Alabama", "49" },
    { "Georgia Southern", "26", "Florida", "20" },
    { "Coastal Carolina", "10", "South Carolina", "70" },
    { "Alabama A+M", "7", "Georgia Tech", "66" },
    { "The Citadel", "6", "Clemson", "52" } };
    
    
    public static final String[] DIVISION_TWO = {
        "Western Carolina",
        "Austin Peay",
        "Nicholls State",
        "Southern Utah",
        "Indiana State",
        "Chattanooga",
        "Weber State",
        "Maine",
        "Tennessee-Martin",
        "Murray State",
        "Cal-San Luis Obispo",
        "Western Illinois",
        "Savannah State",
        "Lamar",
        "Sacramento State",
        "Eastern Washington",
        "Bethune-Cookman",
        "Samford",
        "Northwestern St(LA)",
        "Eastern Illinois",
        "Morgan State",
        "Idaho State",
        "Norfolk State",
        "New Hampshire",
        "Central Arkansas",
        "Jacksonville St",
        "Missouri State",
        "So Carolina State",
        "Alabama A+M",
        "North Dakota St",
        "Fordham",
        "Eastern Kentucky",
        "Florida A+M",
        "Virginia Military",
        "William + Mary",
        "Colgate",
        "Portland State",
        "South Dakota State",
        "Gardner-Webb",
        "Tennessee Tech",
        "South Dakota",
        "Georgia Southern",
        "Montana State",
        "Stephen F Austin",
        "Villanova",
        "Illinois State",
        "Coastal Carolina",
        "James Madison",
        "Northern Iowa",
        "Elon",
        "Howard",
        "Youngstown State",
        "Grambling",
        "Furman",
        "Towson",
        "Charleston Southern",
        "Abilene Christian",
        "S E Missouri St",
        "S E Louisiana",
        "Southern Univ",
        "Prairie View",
        "Northern Colorado",
        "The Citadel",
        "Liberty",
        "Sam Houston State",
        "Alabama State",
        "Northern Arizona",
        "Southern Illinois",
        "Wofford",
        "Presbyterian",
        "Wagner",
        "Stony Brook",
        "Alcorn State",
        "McNeese State",
        "Jackson State",
        "Arkansas-Pine Bluff",
        "Richmond",
        "No Carolina Central",
        "Delaware",
        "Appalachian State",
        "UC-Davis" };
    
    public static final Set<String> DIVISION_TWO_SET = new HashSet<String>();
    
    static {
        for (String s : DIVISION_TWO) {
            DIVISION_TWO_SET.add(s);
        }
    }

}