import java.util.HashSet;
import java.util.Set;

public class Data {

	public static String[][] SCORES = new String[][] {
			{ "Hawaii", "43", "Colorado State", "34" },
			{ "Massachusetts", "63", "Duquesne", "15" },
			{ "Rice", "31", "Prairie View A&M", "28" },
			{ "Wyoming", "29", "New Mexico State", "7" },
			{ "Alabama-Birmingham", "52", "Savannah State", "0" },
			{ "Ball State", "42", "Central Connecticut State", "6" },
			{ "California-Davis", "44", "San Jose State", "38" },
			{ "Central Florida", "56", "Connecticut", "17" },
			{ "Georgia State", "24", "Kennesaw State", "20" },
			{ "Louisiana-Monroe", "34", "Southeastern Louisiana", "31" },
			{ "Minnesota", "48", "New Mexico State", "10" },
			{ "Northwestern", "31", "Purdue", "27" },
			{ "Oklahoma State", "58", "Missouri State", "17" },
			{ "Texas A&M", "59", "Northwestern State", "7" },
			{ "Utah", "41", "Weber State", "10" },
			{ "Wake Forest", "23", "Tulane", "17" },
			{ "Colorado", "45", "Colorado State", "13" },
			{ "Duke", "34", "Army", "14" },
			{ "Eastern Michigan", "51", "Monmouth", "17" },
			{ "Michigan State", "38", "Utah State", "31" },
			{ "Nevada", "72", "Portland State", "19" },
			{ "Stanford", "31", "San Diego State", "10" },
			{ "Syracuse", "55", "Western Michigan", "42" },
			{ "Wisconsin", "34", "Western Kentucky", "3" },
			{ "Air Force", "38", "Stony Brook", "0" },
			{ "Alabama", "51", "Louisville", "14" },
			{ "Arizona State", "49", "Texas-San Antonio", "7" },
			{ "Arkansas", "55", "Eastern Illinois", "20" },
			{ "Arkansas State", "48", "Southeast Missouri State", "21" },
			{ "Auburn", "21", "Washington", "16" },
			{ "Baylor", "55", "Abilene Christian", "27" },
			{ "Boise State", "56", "Troy", "20" },
			{ "Boston College", "55", "Massachusetts", "21" },
			{ "Brigham Young", "28", "Arizona", "23" },
			{ "Buffalo", "48", "Delaware State", "10" },
			{ "California", "24", "North Carolina", "17" },
			{ "Charlotte", "34", "Fordham", "10" },
			{ "Cincinnati", "26", "UCLA", "17" },
			{ "Clemson", "48", "Furman", "7" },
			{ "Florida", "53", "Charleston Southern", "6" },
			{ "Fresno State", "79", "Idaho", "13" },
			{ "Georgia", "45", "Austin Peay", "0" },
			{ "Georgia Southern", "37", "South Carolina State", "6" },
			{ "Georgia Tech", "41", "Alcorn State", "0" },
			{ "Hawaii", "59", "Navy", "41" },
			{ "Houston", "45", "Rice", "27" },
			{ "Illinois", "31", "Kent State", "24" },
			{ "Indiana", "38", "Florida International", "28" },
			{ "Iowa", "33", "Northern Illinois", "7" },
			{ "Kansas State", "27", "South Dakota", "24" },
			{ "Kentucky", "35", "Central Michigan", "20" },
			{ "Liberty", "52", "Old Dominion", "10" },
			{ "Louisiana", "49", "Grambling State", "17" },
			{ "Louisiana Tech", "30", "South Alabama", "26" },
			{ "Marshall", "35", "Miami (OH)", "28" },
			{ "Maryland", "34", "Texas", "29" },
			{ "Memphis", "66", "Mercer", "14" },
			{ "Mississippi", "47", "Texas Tech", "27" },
			{ "Mississippi State", "63", "Stephen F. Austin", "6" },
			{ "Missouri", "51", "Tennessee-Martin", "14" },
			{ "New Mexico", "62", "Incarnate Word", "30" },
			{ "Nicholls State", "26", "Kansas", "23" },
			{ "North Carolina State", "24", "James Madison", "13" },
			{ "North Texas", "46", "Southern Methodist", "23" },
			{ "Northern Arizona", "30", "Texas-El Paso", "10" },
			{ "Notre Dame", "24", "Michigan", "17" },
			{ "Ohio", "38", "Howard", "32" },
			{ "Ohio State", "77", "Oregon State", "31" },
			{ "Oklahoma", "63", "Florida Atlantic", "14" },
			{ "Oregon", "58", "Bowling Green State", "24" },
			{ "Penn State", "45", "Appalachian State", "38" },
			{ "Pittsburgh", "33", "Albany", "7" },
			{ "Rutgers", "35", "Texas State", "7" },
			{ "South Carolina", "49", "Coastal Carolina", "15" },
			{ "South Florida", "34", "Elon", "14" },
			{ "Southern California", "43", "Nevada-Las Vegas", "21" },
			{ "Southern Mississippi", "55", "Jackson State", "7" },
			{ "Texas Christian", "55", "Southern", "7" },
			{ "Toledo", "66", "Virginia Military Institute", "3" },
			{ "Tulsa", "38", "Central Arkansas", "27" },
			{ "Vanderbilt", "35", "Middle Tennessee State", "7" },
			{ "Villanova", "19", "Temple", "17" },
			{ "Virginia", "42", "Richmond", "13" },
			{ "Washington State", "41", "Wyoming", "19" },
			{ "West Virginia", "40", "Tennessee", "14" },
			{ "Louisiana State", "33", "Miami (FL)", "17" },
			{ "North Carolina A&T", "28", "East Carolina", "23" },
			{ "Virginia Tech", "24", "Florida State", "3" },
			{ "Texas Christian", "42", "Southern Methodist", "12" },
			{ "Akron", "41", "Morgan State", "7" },
			{ "Alabama", "57", "Arkansas State", "7" },
			{ "Appalachian State", "45", "Charlotte", "9" },
			{ "Arizona State", "16", "Michigan State", "13" },
			{ "Army", "38", "Liberty", "14" },
			{ "Auburn", "63", "Alabama State", "9" },
			{ "Baylor", "37", "Texas-San Antonio", "20" },
			{ "Boise State", "62", "Connecticut", "7" },
			{ "Boston College", "62", "Holy Cross", "14" },
			{ "Buffalo", "36", "Temple", "29" },
			{ "California", "21", "Brigham Young", "18" },
			{ "Central Florida", "38", "South Carolina State", "0" },
			{ "Cincinnati", "21", "Miami (OH)", "0" },
			{ "Clemson", "28", "Texas A&M", "26" },
			{ "Coastal Carolina", "47", "Alabama-Birmingham", "24" },
			{ "Colorado", "33", "Nebraska", "28" },
			{ "Colorado State", "34", "Arkansas", "27" },
			{ "Duke", "21", "Northwestern", "7" },
			{ "East Carolina", "41", "North Carolina", "19" },
			{ "Eastern Michigan", "20", "Purdue", "19" },
			{ "Florida Atlantic", "33", "Air Force", "27" },
			{ "Florida International", "28", "Old Dominion", "20" },
			{ "Florida State", "36", "Samford", "26" },
			{ "Georgia", "41", "South Carolina", "17" },
			{ "Georgia Southern", "34", "Massachusetts", "13" },
			{ "Hawaii", "43", "Rice", "29" },
			{ "Houston", "45", "Arizona", "18" },
			{ "Illinois", "34", "Western Illinois", "14" },
			{ "Indiana", "20", "Virginia", "16" },
			{ "Iowa", "13", "Iowa State", "3" },
			{ "Kansas", "31", "Central Michigan", "7" },
			{ "Kent State", "54", "Howard", "14" },
			{ "Kentucky", "27", "Florida", "16" },
			{ "Louisiana State", "31", "Southeastern Louisiana", "0" },
			{ "Louisiana Tech", "54", "Southern", "17" },
			{ "Louisiana-Monroe", "21", "Southern Mississippi", "20" },
			{ "Louisville", "31", "Indiana State", "7" },
			{ "Maine", "31", "Western Kentucky", "28" },
			{ "Marshall", "32", "Eastern Kentucky", "16" },
			{ "Maryland", "45", "Bowling Green State", "14" },
			{ "Miami (FL)", "77", "Savannah State", "0" },
			{ "Michigan", "49", "Western Michigan", "3" },
			{ "Middle Tennessee State", "61", "Tennessee-Martin", "37" },
			{ "Minnesota", "21", "Fresno State", "14" },
			{ "Mississippi", "76", "Southern Illinois", "41" },
			{ "Mississippi State", "31", "Kansas State", "10" },
			{ "Missouri", "40", "Wyoming", "13" },
			{ "Navy", "22", "Memphis", "21" },
			{ "Nevada-Las Vegas", "52", "Texas-El Paso", "24" },
			{ "North Carolina State", "41", "Georgia State", "7" },
			{ "North Texas", "58", "Incarnate Word", "16" },
			{ "Notre Dame", "24", "Ball State", "16" },
			{ "Ohio State", "52", "Rutgers", "3" },
			{ "Oklahoma", "49", "UCLA", "21" },
			{ "Oklahoma State", "55", "South Alabama", "13" },
			{ "Oregon", "62", "Portland State", "14" },
			{ "Oregon State", "48", "Southern Utah", "25" },
			{ "Penn State", "51", "Pittsburgh", "6" },
			{ "San Diego State", "28", "Sacramento State", "14" },
			{ "South Florida", "49", "Georgia Tech", "38" },
			{ "Stanford", "17", "Southern California", "3" },
			{ "Syracuse", "62", "Wagner", "10" },
			{ "Tennessee", "59", "East Tennessee State", "3" },
			{ "Texas", "28", "Tulsa", "21" },
			{ "Texas State", "36", "Texas Southern", "20" },
			{ "Texas Tech", "77", "Lamar", "0" },
			{ "Troy", "59", "Florida A&M", "7" },
			{ "Tulane", "42", "Nicholls State", "17" },
			{ "Utah", "17", "Northern Illinois", "6" },
			{ "Utah State", "60", "New Mexico State", "13" },
			{ "Vanderbilt", "41", "Nevada", "10" },
			{ "Virginia Tech", "62", "William & Mary", "17" },
			{ "Wake Forest", "51", "Towson", "20" },
			{ "Washington", "45", "North Dakota", "3" },
			{ "Washington State", "31", "San Jose State", "0" },
			{ "West Virginia", "52", "Youngstown State", "17" },
			{ "Wisconsin", "45", "New Mexico", "14" },
			{ "Boston College", "41", "Wake Forest", "34" },
			{ "Utah State", "73", "Tennessee Tech", "12" },
			{ "Memphis", "59", "Georgia State", "22" },
			{ "Akron", "39", "Northwestern", "34" },
			{ "Alabama", "62", "Mississippi", "7" },
			{ "Alabama-Birmingham", "31", "Tulane", "24" },
			{ "Arizona", "62", "Southern Utah", "31" },
			{ "Arkansas State", "29", "Tulsa", "20" },
			{ "Army", "28", "Hawaii", "21" },
			{ "Bowling Green State", "42", "Eastern Kentucky", "35" },
			{ "Brigham Young", "24", "Wisconsin", "21" },
			{ "Buffalo", "35", "Eastern Michigan", "28" },
			{ "California", "45", "Idaho State", "23" },
			{ "Campbell", "58", "Coastal Carolina", "21" },
			{ "Charlotte", "28", "Old Dominion", "25" },
			{ "Cincinnati", "63", "Alabama A&M", "7" },
			{ "Clemson", "38", "Georgia Southern", "7" },
			{ "Colorado", "45", "New Hampshire", "14" },
			{ "Connecticut", "56", "Rhode Island", "49" },
			{ "Duke", "40", "Baylor", "27" },
			{ "Florida", "48", "Colorado State", "10" },
			{ "Florida Atlantic", "49", "Bethune-Cookman", "28" },
			{ "Florida International", "63", "Massachusetts", "24" },
			{ "Fresno State", "38", "UCLA", "14" },
			{ "Georgia", "49", "Middle Tennessee State", "7" },
			{ "Indiana", "38", "Ball State", "10" },
			{ "Iowa", "38", "Northern Iowa", "14" },
			{ "Kansas", "55", "Rutgers", "14" },
			{ "Kansas State", "41", "Texas-San Antonio", "17" },
			{ "Kentucky", "48", "Murray State", "10" },
			{ "Louisiana State", "22", "Auburn", "21" },
			{ "Louisville", "20", "Western Kentucky", "17" },
			{ "Miami (FL)", "49", "Toledo", "24" },
			{ "Michigan", "45", "Southern Methodist", "20" },
			{ "Minnesota", "26", "Miami (OH)", "3" },
			{ "Mississippi State", "56", "Louisiana", "10" },
			{ "Missouri", "40", "Purdue", "37" },
			{ "Navy", "51", "Lehigh", "21" },
			{ "Nevada", "37", "Oregon State", "35" },
			{ "Nevada-Las Vegas", "46", "Prairie View A&M", "17" },
			{ "New Mexico", "42", "New Mexico State", "25" },
			{ "North Texas", "44", "Arkansas", "17" },
			{ "Northern Illinois", "24", "Central Michigan", "16" },
			{ "Notre Dame", "22", "Vanderbilt", "17" },
			{ "Ohio State", "40", "Texas Christian", "28" },
			{ "Oklahoma", "37", "Iowa State", "27" },
			{ "Oklahoma State", "44", "Boise State", "21" },
			{ "Oregon", "35", "San Jose State", "22" },
			{ "Penn State", "63", "Kent State", "10" },
			{ "Pittsburgh", "24", "Georgia Tech", "19" },
			{ "San Diego State", "28", "Arizona State", "21" },
			{ "South Alabama", "41", "Texas State", "31" },
			{ "South Florida", "25", "Illinois", "19" },
			{ "Stanford", "30", "California-Davis", "10" },
			{ "Syracuse", "30", "Florida State", "7" },
			{ "Temple", "35", "Maryland", "14" },
			{ "Tennessee", "24", "Texas-El Paso", "0" },
			{ "Texas", "37", "Southern California", "14" },
			{ "Texas A&M", "48", "Louisiana-Monroe", "10" },
			{ "Texas Tech", "63", "Houston", "49" },
			{ "Troy", "24", "Nebraska", "19" },
			{ "Virginia", "45", "Ohio", "31" },
			{ "Washington", "21", "Utah", "7" },
			{ "Washington State", "59", "Eastern Washington", "24" },
			{ "Western Michigan", "68", "Delaware State", "0" },
			{ "Wyoming", "17", "Wofford", "14" } };

	private static final String[] FCS = { "Texas Southern", "Western Carolina", "Austin Peay",
			"Nicholls State", "Southern Utah", "Indiana State", "Chattanooga",
			"Weber State", "Maine", "Tennessee-Martin", "Murray State",
			"Cal-San Luis Obispo", "Western Illinois", "Savannah State",
			"Lamar", "Sacramento State", "Eastern Washington",
			"Bethune-Cookman", "Samford", "Northwestern St(LA)",
			"Eastern Illinois", "Morgan State", "Idaho State", "Norfolk State",
			"New Hampshire", "Central Arkansas", "Jacksonville St",
			"Missouri State", "So Carolina State", "Alabama A+M",
			"North Dakota St", "Fordham", "Eastern Kentucky", "Florida A+M",
			"Virginia Military", "William + Mary", "Colgate", "Portland State",
			"South Dakota State", "Gardner-Webb", "Tennessee Tech",
			"South Dakota", "Montana State", "Stephen F Austin", "Villanova",
			"Illinois State", "James Madison", "Northern Iowa", "Elon",
			"Howard", "Youngstown State", "Grambling", "Furman", "Towson",
			"Charleston Southern", "Abilene Christian", "S E Missouri St",
			"S E Louisiana", "Southern Univ", "Prairie View",
			"Northern Colorado", "The Citadel", "Sam Houston State",
			"Alabama State", "Northern Arizona", "Southern Illinois",
			"Wofford", "Presbyterian", "Wagner", "Stony Brook", "Alcorn State",
			"McNeese State", "Jackson State", "Arkansas-Pine Bluff",
			"Richmond", "No Carolina Central", "Delaware", "UC-Davis",
			"North Dakota State", "Incarnate Word", "Rhode Island", "Monmouth",
			"Grambling State", "Southern", "North Dakota", "Cal Poly",
			"Delaware State", "Virginia Military Institute",
			"Stephen F. Austin", "Lafayette", "Prairie View A&M",
			"Northwestern State", "William & Mary", "Tennessee State",
			"Houston Baptist", "California-Davis", "Mississippi Valley State",
			"Florida A&M", "Citadel", "Hampton", "Southeast Missouri State",
			"Mercer", "Alabama A&M", "North Carolina Central",
			"Southeastern Louisiana", "Jacksonville State", "Albany",
			"North Carolina A&T", "South Carolina State", "Holy Cross",
			"Central Connecticut State", "Montana", "Idaho", "Lehigh", "Duquesne",
			"East Tennessee State", "Kennesaw State", "Campbell", "Southern Mississippi"};

	public static final Set<String> FCS_TEAMS = new HashSet<String>();

	static {
		for (String s : FCS) {
			FCS_TEAMS.add(s);
		}
	}

}