import java.util.HashSet;
import java.util.Set;

public class Data {

	public static String[][] SCORES = new String[][] {
		{"Hawaii","45","Arizona","38"},
		{"Miami (FL)","24","Florida","20"},
		{"Alabama-Birmingham","24","Alabama State","19"},
		{"Arizona State","30","Kent State","7"},
		{"Bowling Green State","46","Morgan State","3"},
		{"Buffalo","38","Robert Morris","10"},
		{"Central Arkansas","35","Western Kentucky","28"},
		{"Central Florida","62","Florida A&M","0"},
		{"Central Michigan","38","Albany","21"},
		{"Cincinnati","24","UCLA","14"},
		{"Clemson","52","Georgia Tech","14"},
		{"Connecticut","24","Wagner","21"},
		{"Minnesota","28","South Dakota State","21"},
		{"San Jose State","35","Northern Colorado","18"},
		{"Texas A&M","41","Texas State","7"},
		{"Tulane","42","Florida International","14"},
		{"Utah","30","Brigham Young","12"},
		{"Army","14","Rice","7"},
		{"Colorado","52","Colorado State","31"},
		{"Michigan State","28","Tulsa","7"},
		{"Nevada","34","Purdue","31"},
		{"Oklahoma State","52","Oregon State","36"},
		{"Rutgers","48","Massachusetts","21"},
		{"Wake Forest","38","Utah State","35"},
		{"Wisconsin","49","South Florida","0"},
		{"Air Force","48","Colgate","7"},
		{"Appalachian State","42","East Tennessee State","7"},
		{"Arkansas","20","Portland State","13"},
		{"Baylor","56","Stephen F. Austin","17"},
		{"Boise State","36","Florida State","31"},
		{"Boston College","35","Virginia Tech","28"},
		{"California","27","California-Davis","13"},
		{"Charlotte","49","Gardner-Webb","28"},
		{"Duke","42","Alabama","3"},
		{"Eastern Michigan","30","Coastal Carolina","23"},
		{"Georgia","30","Vanderbilt","6"},
		{"Georgia State","38","Tennessee","30"},
		{"Illinois","42","Akron","3"},
		{"Indiana","34","Ball State","24"},
		{"Iowa","38","Miami (OH)","14"},
		{"Iowa State","29","Northern Iowa","26"},
		{"Kansas","24","Indiana State","17"},
		{"Kansas State","49","Nicholls State","14"},
		{"Kentucky","38","Toledo","24"},
		{"Louisiana State","55","Georgia Southern","3"},
		{"Louisiana-Monroe","31","Grambling State","9"},
		{"Marshall","56","Virginia Military Institute","17"},
		{"Maryland","79","Howard","0"},
		{"Memphis","15","Mississippi","10"},
		{"Michigan","40","Middle Tennessee State","21"},
		{"Mississippi State","38","Louisiana","28"},
		{"Navy","45","Holy Cross","7"},
		{"Nebraska","35","South Alabama","21"},
		{"Nevada-Las Vegas","56","Southern Utah","23"},
		{"New Mexico","39","Sam Houston State","31"},
		{"North Carolina","24","South Carolina","20"},
		{"North Carolina State","34","East Carolina","6"},
		{"North Texas","51","Abilene Christian","31"},
		{"Northern Illinois","24","Illinois State","10"},
		{"Ohio","41","Rhode Island","20"},
		{"Ohio State","45","Florida Atlantic","21"},
		{"Old Dominion","24","Norfolk State","21"},
		{"Oregon","27","Auburn","21"},
		{"Penn State","79","Idaho","7"},
		{"San Diego State","6","Weber State","0"},
		{"Southern California","31","Fresno State","23"},
		{"Southern Methodist","37","Arkansas State","30"},
		{"Southern Mississippi","38","Alcorn State","10"},
		{"Stanford","17","Northwestern","7"},
		{"Syracuse","24","Liberty","0"},
		{"Temple","56","Bucknell","12"},
		{"Texas","45","Louisiana Tech","14"},
		{"Texas Christian","39","Arkansas-Pine Bluff","7"},
		{"Texas Tech","45","Montana State","10"},
		{"Texas-El Paso","36","Houston Baptist","34"},
		{"Texas-San Antonio","35","Incarnate Word","7"},
		{"Troy","43","Campbell","14"},
		{"Virginia","30","Pittsburgh","14"},
		{"Washington","47","Eastern Washington","14"},
		{"Washington State","58","New Mexico State","7"},
		{"West Virginia","20","James Madison","13"},
		{"Western Michigan","48","Monmouth","13"},
		{"Wyoming","37","Missouri","31"},
		{"Oklahoma","49","Houston","31"},
		{"Notre Dame","35","Louisville","17"},
		{"Arizona State","19","Sacramento State","7"},
		{"Boise State","14","Marshall","7"},
		{"Virginia","52","William & Mary","17"},
		{"Wake Forest","41","Rice","21"},
		{"Alabama","62","New Mexico State","10"},
		{"Alabama-Birmingham","31","Akron","20"},
		{"Appalachian State","56","Charlotte","41"},
		{"Arizona","65","Northern Arizona","41"},
		{"Arkansas State","43","Nevada-Las Vegas","17"},
		{"Auburn","24","Tulane","6"},
		{"Ball State","57","Fordham","29"},
		{"Baylor","63","Texas-San Antonio","14"},
		{"Boston College","45","Richmond","13"},
		{"Brigham Young","29","Tennessee","26"},
		{"California","20","Washington","19"},
		{"Central Florida","48","Florida Atlantic","14"},
		{"Clemson","24","Texas A&M","10"},
		{"Coastal Carolina","12","Kansas","7"},
		{"Colorado","34","Nebraska","31"},
		{"Colorado State","38","Western Illinois","13"},
		{"Duke","45","North Carolina A&T","13"},
		{"East Carolina","48","Gardner-Webb","9"},
		{"Florida","45","Tennessee-Martin","0"},
		{"Florida State","45","Louisiana-Monroe","44"},
		{"Georgia","63","Murray State","17"},
		{"Georgia Southern","26","Maine","18"},
		{"Georgia State","48","Furman","42"},
		{"Georgia Tech","14","South Florida","10"},
		{"Hawaii","31","Oregon State","28"},
		{"Houston","37","Prairie View A&M","17"},
		{"Illinois","31","Connecticut","23"},
		{"Indiana","52","Eastern Illinois","0"},
		{"Iowa","30","Rutgers","0"},
		{"Kansas State","52","Bowling Green State","0"},
		{"Kent State","26","Kennesaw State","23"},
		{"Kentucky","38","Eastern Michigan","17"},
		{"Louisiana","35","Liberty","14"},
		{"Louisiana State","45","Texas","38"},
		{"Louisiana Tech","20","Grambling State","14"},
		{"Louisville","42","Eastern Kentucky","0"},
		{"Maryland","63","Syracuse","20"},
		{"Memphis","55","Southern","24"},
		{"Miami (OH)","48","Tennessee Tech","17"},
		{"Michigan","24","Army","21"},
		{"Michigan State","51","Western Michigan","17"},
		{"Middle Tennessee State","45","Tennessee State","26"},
		{"Minnesota","38","Fresno State","35"},
		{"Mississippi","31","Arkansas","17"},
		{"Mississippi State","38","Southern Mississippi","15"},
		{"Missouri","38","West Virginia","7"},
		{"North Carolina","28","Miami (FL)","25"},
		{"North Carolina State","41","Western Carolina","0"},
		{"Ohio State","42","Cincinnati","0"},
		{"Oklahoma","70","South Dakota","14"},
		{"Oklahoma State","56","McNeese State","14"},
		{"Oregon","77","Nevada","6"},
		{"Penn State","45","Buffalo","13"},
		{"Pittsburgh","20","Ohio","10"},
		{"Purdue","42","Vanderbilt","24"},
		{"San Diego State","23","UCLA","14"},
		{"South Alabama","37","Jackson State","14"},
		{"South Carolina","72","Charleston Southern","10"},
		{"Southern California","45","Stanford","20"},
		{"Southern Illinois","45","Massachusetts","20"},
		{"Southern Methodist","49","North Texas","27"},
		{"Texas Tech","38","Texas-El Paso","3"},
		{"Tulsa","34","San Jose State","16"},
		{"Utah","35","Northern Illinois","17"},
		{"Utah State","62","Stony Brook","7"},
		{"Virginia Tech","31","Old Dominion","17"},
		{"Washington State","59","Northern Colorado","17"},
		{"Western Kentucky","20","Florida International","14"},
		{"Wisconsin","61","Central Michigan","0"},
		{"Wyoming","23","Texas State","14"},
		{"Kansas","48","Boston College","24"},
		{"Wake Forest","24","North Carolina","18"},
		{"Washington State","31","Houston","24"},
		{"Air Force","30","Colorado","23"},
		{"Alabama","47","South Carolina","23"},
		{"Arizona","28","Texas Tech","14"},
		{"Arizona State","10","Michigan State","7"},
		{"Arkansas","55","Colorado State","34"},
		{"Army","31","Texas-San Antonio","13"},
		{"Auburn","55","Kent State","16"},
		{"Boise State","45","Portland State","10"},
		{"Brigham Young","30","Southern California","27"},
		{"California","23","North Texas","17"},
		{"Central Florida","45","Stanford","27"},
		{"Central Michigan","45","Akron","24"},
		{"Charlotte","52","Massachusetts","17"},
		{"Cincinnati","35","Miami (OH)","13"},
		{"Citadel","27","Georgia Tech","24"},
		{"Clemson","41","Syracuse","6"},
		{"Coastal Carolina","46","Norfolk State","7"},
		{"Duke","41","Middle Tennessee State","18"},
		{"Eastern Michigan","34","Illinois","31"},
		{"Florida","29","Kentucky","21"},
		{"Florida Atlantic","41","Ball State","31"},
		{"Florida International","30","New Hampshire","17"},
		{"Georgia","55","Arkansas State","0"},
		{"Iowa","18","Iowa State","17"},
		{"Kansas State","31","Mississippi State","24"},
		{"Liberty","35","Buffalo","17"},
		{"Louisiana","77","Texas Southern","6"},
		{"Louisiana State","65","Northwestern State","14"},
		{"Louisiana Tech","35","Bowling Green State","7"},
		{"Louisville","38","Western Kentucky","21"},
		{"Marshall","33","Ohio","31"},
		{"Memphis","42","South Alabama","6"},
		{"Miami (FL)","63","Bethune-Cookman","0"},
		{"Minnesota","35","Georgia Southern","32"},
		{"Mississippi","40","Southeastern Louisiana","29"},
		{"Missouri","50","Southeast Missouri State","0"},
		{"Navy","42","East Carolina","10"},
		{"Nebraska","44","Northern Illinois","8"},
		{"Nevada","19","Weber State","13"},
		{"Northwestern","30","Nevada-Las Vegas","14"},
		{"Notre Dame","66","New Mexico","14"},
		{"Ohio State","51","Indiana","10"},
		{"Oklahoma","48","UCLA","14"},
		{"Oklahoma State","40","Tulsa","21"},
		{"Oregon","35","Montana","3"},
		{"Oregon State","45","Cal Poly","7"},
		{"Penn State","17","Pittsburgh","10"},
		{"Rice","48","Texas","13"},
		{"San Diego State","31","New Mexico State","10"},
		{"South Florida","55","South Carolina State","16"},
		{"Southern Methodist","47","Texas State","17"},
		{"Southern Mississippi","47","Troy","42"},
		{"Temple","20","Maryland","17"},
		{"Tennessee","45","Chattanooga","0"},
		{"Texas A&M","62","Lamar","3"},
		{"Texas Christian","34","Purdue","13"},
		{"Toledo","45","Murray State","0"},
		{"Tulane","58","Missouri State","6"},
		{"Utah","31","Idaho State","0"},
		{"Virginia","31","Florida State","24"},
		{"Virginia Tech","24","Furman","17"},
		{"Washington","52","Hawaii","20"},
		{"West Virginia","44","North Carolina State","27"},
		{"Western Michigan","57","Georgia State","10"},
		{"Wyoming","21","Idaho","16"} };

		private static final String[] FCS = { "Texas Southern", "Western Carolina", "Austin Peay",
				"Nicholls State", "Southern Utah", "Indiana State", "Chattanooga",
				"Weber State", "Maine", "Tennessee-Martin", "Murray State",
				"Cal-San Luis Obispo", "Western Illinois", "Savannah State",
				"Lamar", "Sacramento State", "Eastern Washington",
				"Bethune-Cookman", "Samford", "Northwestern St(LA)",
				"Eastern Illinois", "Morgan State", "Idaho State", "Norfolk State",
				"New Hampshire", "Central Arkansas", "Jacksonville St",
				"Missouri State", "So Carolina State", "Alabama A+M",
				"North Dakota St", "Fordham", "Eastern Kentucky", "Florida A+M",
				"Virginia Military", "William + Mary", "Colgate", "Portland State",
				"South Dakota State", "Gardner-Webb", "Tennessee Tech",
				"South Dakota", "Montana State", "Stephen F Austin", "Villanova",
				"Illinois State", "James Madison", "Northern Iowa", "Elon",
				"Howard", "Youngstown State", "Grambling", "Furman", "Towson",
				"Charleston Southern", "Abilene Christian", "S E Missouri St",
				"S E Louisiana", "Southern Univ", "Prairie View",
				"Northern Colorado", "The Citadel", "Sam Houston State",
				"Alabama State", "Northern Arizona", "Southern Illinois",
				"Wofford", "Presbyterian", "Wagner", "Stony Brook", "Alcorn State",
				"McNeese State", "Jackson State", "Arkansas-Pine Bluff",
				"Richmond", "No Carolina Central", "Delaware", "UC-Davis",
				"North Dakota State", "Incarnate Word", "Rhode Island", "Monmouth",
				"Grambling State", "Southern", "North Dakota", "Cal Poly",
				"Delaware State", "Virginia Military Institute",
				"Stephen F. Austin", "Lafayette", "Prairie View A&M",
				"Northwestern State", "William & Mary", "Tennessee State",
				"Houston Baptist", "California-Davis", "Mississippi Valley State",
				"Florida A&M", "Citadel", "Hampton", "Southeast Missouri State",
				"Mercer", "Alabama A&M", "North Carolina Central",
				"Southeastern Louisiana", "Jacksonville State", "Albany",
				"North Carolina A&T", "South Carolina State", "Holy Cross",
				"Central Connecticut State", "Montana", "Idaho", "Lehigh", "Duquesne",
				"East Tennessee State", "Kennesaw State", "Campbell", "Southern Mississippi",
			  "Robert Morris"};

		public static final Set<String> FCS_TEAMS = new HashSet<String>();

		static {
			for (String s : FCS) {
				FCS_TEAMS.add(s);
			}
		}

}
